name: Assemble Datav

on:
  push:
    paths:
      - 'taotao-cloud-ui/taotao-cloud-vue3-datav/**'
  pull_request:
    branches: [ datav ]
    #branches: [ master ]

  workflow_dispatch:

defaults:
  run:
    working-directory: ./taotao-cloud-ui/taotao-cloud-vue3-datav

jobs:
  assemble:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'taotao-cloud-datav') }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Node_modules Folder
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/node_modules
          key: ${{ runner.os }}-node_modules
          restore-keys: ${{ runner.os }}-node_modules

      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn
        uses: actions/cache@v3
        env:
          cache-name: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Yarn Install And Build
        run: |
          yarn
          yarn build

      - name: Deploy To Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_DATAV_TARGET }}

#      - name: Deploy
#        uses: SamKirkland/FTP-Deploy-Action@2.0.0
#        env:
#          FTP_SERVER: ${{ secrets.FTP_SERVER }}
#          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
#          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
#          METHOD: sftp
#          PORT: ${{ secrets.FTP_PORT }}
#          LOCAL_DIR: dist
#          REMOTE_DIR: /srv/www/vben-admin
#          ARGS: --delete --verbose --parallel=80
