name: Qodana Code Quality
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - quality
      #- master
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'taotao-cloud-qodana') }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v5.1.0
        with:
          #args: "--project-dir ${{ github.workflow }}/taotao-cloud-microservice"
          results-dir: ${{ github.workspace }}/qodana/results

      - name: Upload Sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ github.workspace }}/qodana/results/qodana.sarif.json

      - name: Deploy To GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TAOTAO_CLOUD_GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/qodana/results/report
          destination_dir: ./

      - name: Deploy To Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "qodana/results/report/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_QODANA_TARGET }}
